library(shiny)
library(shinythemes)
library(Benchmarking)
library(ggplot2)
library(dplyr)
library(reshape2)
library(psych)
library(nFactors)
library(readr)
library(scales)
library(xtable)
library(corrplot)
library(gridExtra)
library(randomForest)
library(rpart.plot)
library(GPArotation)
library(extrafont)

shinyServer(function(input, output) {
  #重整路徑
  setwd("C:/Users/user/Documents/GitHub/Data_analysis")
  source('tabDEA.R', local=TRUE, encoding = "utf-8")
  source('tabFA.R', local=TRUE, encoding = "utf-8")
  source('tabRF.R', local=TRUE, encoding = "utf-8")
  source('tabFQA.R', local=TRUE, encoding = "utf-8")
  source('tabSINDEA.R',local=TRUE , encoding = "utf-8")
  source('tabMovingAverage.R',local=TRUE , encoding = "utf-8")
  source('tabSTAFF.R',local=TRUE , encoding = "utf-8")
})
