library(shiny)
library(shinythemes)
library(Benchmarking)
library(ggplot2)
library(dplyr)
library(reshape2)
library(psych)
library(nFactors)
library(data.table)
# library(readr)
library(scales)
library(xtable)
library(corrplot)
library(gridExtra)
library(randomForest)
library(rpart.plot)
library(GPArotation)
library(riverplot)
library(RColorBrewer)
library(waffle)

windowsFonts(BL = windowsFont("微軟正黑體"))

shinyServer(function(input, output) {
  #重整路徑
<<<<<<< HEAD
  #setwd("C:/Users/asus/Documents/GitHub/Data_analysis")
=======
  setwd("C:/Users/asus/Documents/GitHub/Data_analysis")
>>>>>>> upstream/master
  options(scipen = 10)
  source('tabDEA.R', local=TRUE, encoding = "utf-8")
  source('tabFA.R', local=TRUE, encoding = "utf-8")
  source('tabRF.R', local=TRUE, encoding = "utf-8")
  source('tabFQA.R', local=TRUE, encoding = "utf-8")
  source('tabSINDEA.R',local=TRUE , encoding = "utf-8")
  source('tabMovingAverage.R',local=TRUE , encoding = "utf-8")
  source('tabSTAFF.R',local=TRUE , encoding = "utf-8")
  source('tabDrawGraph.R', local=TRUE, encoding = "utf-8")
  source('tabCABINET.R', local=TRUE, encoding = "utf-8")
  source('tabJOURNEY.R', local=TRUE, encoding = "utf-8")
})
