library(shiny)
library(shinythemes)
shinyServer(function(input, output) {
  source('tabDEA.R', local=TRUE, encoding = "utf-8")
  source('tabFA.R', local=TRUE, encoding = "utf-8")
  source('tabRF.R', local=TRUE, encoding = "utf-8")
  source('tabFQA.R', local=TRUE, encoding = "utf-8")
  source('tabSINDEA.R',local=TRUE , encoding = "utf-8")
  source('tabMovingAverage.R',local=TRUE , encoding = "utf-8")
  source('tabSTAFF.R',local=TRUE , encoding = "utf-8")
})
